Change CI for sync image (#31)

diff --git a/.github/workflows/build_and_push_manylinux.yml b/.github/workflows/build_and_push_manylinux.yml
--- a/.github/workflows/build_and_push_manylinux.yml
+++ b/.github/workflows/build_and_push_manylinux.yml
@@ -15,18 +15,18 @@ on:
           - 8.2.rc1.alpha003-310p-manylinux_2_28-py3.11
           - 8.2.rc1.alpha003-310p-manylinux_2_28-py3.10
           - 8.2.rc1.alpha003-310p-manylinux_2_28-py3.9
-          - 8.0.0-310p-manylinux_2_28-py3.11
-          - 8.0.0-310p-manylinux_2_28-py3.10
-          - 8.0.0-310p-manylinux_2_28-py3.9
+          - 8.1.rc1-910b-manylinux_2_28-py3.11
+          - 8.1.rc1-910b-manylinux_2_28-py3.10
+          - 8.1.rc1-910b-manylinux_2_28-py3.9
           - 8.1.rc1-310p-manylinux_2_28-py3.11
           - 8.1.rc1-310p-manylinux_2_28-py3.10
           - 8.1.rc1-310p-manylinux_2_28-py3.9
           - 8.0.0-910b-manylinux_2_28-py3.11
           - 8.0.0-910b-manylinux_2_28-py3.10
           - 8.0.0-910b-manylinux_2_28-py3.9
-          - 8.1.rc1-910b-manylinux_2_28-py3.11
-          - 8.1.rc1-910b-manylinux_2_28-py3.10
-          - 8.1.rc1-910b-manylinux_2_28-py3.9
+          - 8.0.0-310p-manylinux_2_28-py3.11
+          - 8.0.0-310p-manylinux_2_28-py3.10
+          - 8.0.0-310p-manylinux_2_28-py3.9
       publish:
         description: 'Publish the image'
         default: false
@@ -88,13 +88,6 @@ jobs:
           password: ${{ secrets.QUAY_TOKEN }}
           ecr: false
           logout: false
-    
-      - name: Login to Huawei Cloud SWR
-        uses: docker/login-action@v3
-        with:
-          registry: swr.cn-southwest-2.myhuaweicloud.com
-          username: ${{ secrets.HW_USERNAME }}
-          password: ${{ secrets.HW_TOKEN }}
 
       - name: Build and push by digest
         uses: docker/build-push-action@v6
@@ -103,7 +96,6 @@ jobs:
           platforms: ${{ matrix.arch }}
           tags: |
             quay.io/ascend/manylinux
-            swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/manylinux
           file: ${{ github.workspace }}/manylinux/${{ inputs.cann_tag }}/Dockerfile
           context: ${{ github.workspace }}/manylinux/${{ inputs.cann_tag }}
           outputs: type=image,push-by-digest=true,name-canonical=true,push=true
@@ -144,56 +136,54 @@ jobs:
           username: ${{ secrets.QUAY_USERNAME }}
           password: ${{ secrets.QUAY_TOKEN }}
 
-      - name: Login to Huawei Cloud SWR
-        uses: docker/login-action@v3
-        with:
-          registry: swr.cn-southwest-2.myhuaweicloud.com
-          username: ${{ secrets.HW_USERNAME }}
-          password: ${{ secrets.HW_TOKEN }}
-
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       - name: Prepare tags
         id: prepare-tags
         run: |
-            BASE_TAGS=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
-              '.versions[] | select(.path == "manylinux/" + $cann_tag) | .tags[]' \
-              manylinux_publish_version.json)
-            registries=(
-              "quay.io/ascend/manylinux"
-              "swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/manylinux"
-            )
-            first=true
-            TAGS_JSON="["
-            for registry in "${registries[@]}"; do
-              for tag in $(echo "$BASE_TAGS" | tr ',' ' '); do
-                if [ "$first" != true ]; then
-                  TAGS_JSON+=","
-                fi
-                TAGS_JSON+="\"${registry}:${tag}\""
-                first=false
-              done
-            done
-            TAGS_JSON+="]"
-            echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
+          BASE_TAG=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
+            '.versions[] | select(.path == "manylinux/" + $cann_tag) | .tags[0]' \
+            manylinux_publish_version.json)
+          registry="quay.io/ascend/manylinux"
+          TAGS_JSON="[\"${registry}:${BASE_TAG}\"]"
+          echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
 
       - name: Create manifest list and push
         working-directory: ${{ runner.temp }}/digests
         env:
           TAGS: ${{ steps.prepare-tags.outputs.tags }}
         run: |
-          readarray -t TAGS_ARRAY <<< "$(echo "$TAGS" | jq -r '.[]')"
+          TAG=$(echo "$TAGS" | jq -r '.[0]')
+          if [[ "$TAG" == *"quay.io/ascend/manylinux"* ]]; then
+            docker buildx imagetools create -t "$TAG" \
+              $(printf 'quay.io/ascend/manylinux@sha256:%s ' *)
+          else
+            echo "Error: Unknown registry in TAG: $TAG"
+            exit 1
+          fi
 
-          for TAG in "${TAGS_ARRAY[@]}"; do
-            if [[ "$TAG" == *"quay.io/ascend/manylinux"* ]]; then
-              docker buildx imagetools create -t "$TAG" \
-                $(printf 'quay.io/ascend/manylinux@sha256:%s ' *)
-            elif [[ "$TAG" == *"swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/manylinux"* ]]; then
-              docker buildx imagetools create -t "$TAG" \
-                $(printf 'swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/manylinux@sha256:%s ' *)
-            else
-              echo "Error: Unknown registry in TAG: $TAG"
-              exit 1
-            fi
-          done
+  sync-image:
+    runs-on: ubuntu-latest
+    needs: push-image
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install skopeo
+        run: |
+          sudo apt update
+          sudo apt install -y skopeo
+
+      - name: Login to Huawei Cloud SWR
+        run: |
+          echo "${{ secrets.HW_TOKEN }}" | skopeo login \
+            --username "${{ secrets.HW_USERNAME }}" \
+            --password-stdin \
+            swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci
+
+      - name: Sync image
+        run: |
+          skopeo copy --all \
+          docker://quay.io/ascend/manylinux:${{ inputs.cann_tag }} \
+          docker://swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/manylinux:${{ inputs.cann_tag }}
